name: renovation_core
description: The missing SDK developers have been longing for to interact with Frappe/ERPNext
version: 1.2.4
homepage: https://github.com/leam-tech/renovation_core.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.6
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  socket_io_client: ^2.0.3+1
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path: ^1.6.4
  logger: ^2.0.2+1
  meta: ^1.1.8
  enum_to_string: ^2.0.1
  pedantic: ^1.8.0
  zxcvbn: ^1.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.12.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
